### ISSUE TITLE
Incorrect value example of `_atom_site_moment_fourier_param.cos_symmform`

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/magnetic_dic#67]
The `_description_example.case` attribute is used in two slightly different ways:
- In data item definitions it provides example values.
- In category definitions it provides excerpts from CIF files that demonstrate how items from the given category may be used.

Currently, the definition of the  `_atom_site_moment_fourier_param.cos_symmform` data item incorrectly provides a CIF excerpt:
```
    loop_
    _cell_wave_vector_seq_id
    _cell_wave_vector_x
# ...
    _atom_site_moment_Fourier_param.sin
    _atom_site_moment_Fourier_param.cos_symmform
    _atom_site_moment_Fourier_param.sin_symmform
    1  Fe_1 1 x  0.00000  0.84852  0            mxs1
    2  Fe_1 1 y  0.00000  0.42426  0            0.50000*mxs1
    3  Fe_1 1 z  0.00000  0.00000  0            0
    4  Fe_1 2 x  0.00000 -0.42426  0           -0.50000*mxs1
    5  Fe_1 2 y  0.00000 -0.84852  0           -mxs1
# ...
```

It would be best to replace this example with one or two examples of cos symmform values and, if possible, human readable explanations, e.g. as is done with the `_atom_site_moment.symmform` data item:
```
    loop_
      _description_example.case
      _description_example.detail
         mx,my,mz
;
         no symmetry restrictions
;
         mx,-mx,0
;
         y component equal and opposite to x component
          with z component zero
;
``` 
Alternatively, we could remove this example, since a very similar example with an CIF excerpt is already provided in the `ATOM_SITE_MOMENT_FOURIER_PARAM` category example.

@brantonc, could you please provide a few symmform value examples and their human-readable descriptions? (Or is the `ATOM_SITE_MOMENT_FOURIER_PARAM` category example alone is already sufficient?)

**Comment by brantonc** [comment]
Thank you.  I apologize for the slow reply.

In magCIF 0.9.8, I don’t a CIF excerpt for  _atom_site_moment_fourier_param.cos_symmform.
https://www.iucr.org/__data/iucr/cifdic_html/3/MAGNETIC_CIF/Iatom_site_moment_Fourier_param.cos_symmform.html

Rather, I see a human-readable explanation of the symmform values.  I can certainly add some example values with explanation.  Please confirm that you want me to do this.

Best wishes,
Branton

From: Antanas Vaitkus ***@***.***>
Sent: Monday, January 22, 2024 9:23 AM
To: COMCIFS/magnetic_dic ***@***.***>
Cc: Branton Campbell ***@***.***>; Mention ***@***.***>
Subject: [COMCIFS/magnetic_dic] Incorrect value example of `_atom_site_moment_fourier_param.cos_symmform` (Issue #67)


The _description_example.case attribute is used in two slightly different ways:

  *   In data item definitions it provides example values.
  *   In category definitions it provides excerpts from CIF files that demonstrate how items from the given category may be used.

Currently, the definition of the _atom_site_moment_fourier_param.cos_symmform data item incorrectly provides a CIF excerpt:

    loop_

    _cell_wave_vector_seq_id

    _cell_wave_vector_x

# ...

    _atom_site_moment_Fourier_param.sin

    _atom_site_moment_Fourier_param.cos_symmform

    _atom_site_moment_Fourier_param.sin_symmform

    1  Fe_1 1 x  0.00000  0.84852  0            mxs1

    2  Fe_1 1 y  0.00000  0.42426  0            0.50000*mxs1

    3  Fe_1 1 z  0.00000  0.00000  0            0

    4  Fe_1 2 x  0.00000 -0.42426  0           -0.50000*mxs1

    5  Fe_1 2 y  0.00000 -0.84852  0           -mxs1

# ...

It would be best to replace this example with one or two examples of cos symmform values and, if possible, human readable explanations, e.g. as is done with the _atom_site_moment.symmform data item:

    loop_

      _description_example.case

      _description_example.detail

         mx,my,mz

;

         no symmetry restrictions

;

         mx,-mx,0

;

         y component equal and opposite to x component

          with z component zero

;

Alternatively, we could remove this example, since a very similar example with an CIF excerpt is already provided in the ATOM_SITE_MOMENT_FOURIER_PARAM category example.

@brantonc<https://github.com/brantonc>, could you please provide a few symmform value examples and their human-readable descriptions? (Or is the ATOM_SITE_MOMENT_FOURIER_PARAM category example alone is already sufficient?)

**Comment by vaitkus** [comment]
Firstly, let me apologise if my original issue report looks malformed -- I am using the GitHub web interface and it renders great there, however, I am not sure if all the visual formatting translates well in an email.

The magCIF 0.9.8 on the IUCr website that you linked indeed does not have this problem, it is only present in this repository. Specifically, the updated definition now contains the `_description_example.case` attribute with a quite unusual value. One would expect examples to be simple value-explanation pairs of a similar form to those given for the `_atom_site_moment.symmform` item (see "Example" section in https://www.iucr.org/__data/iucr/cifdic_html/3/MAGNETIC_CIF/Iatom_site_moment.symmform.html), but instead a category-like example with multiple data names and values is provided (e.g. similar to the one in https://www.iucr.org/__data/iucr/cifdic_html/3/MAGNETIC_CIF/CATOM_SITE_MOMENT_FOURIER_PARAM.html).

So if you would provide several `_atom_site_moment_fourier_param.cos_symmform` examples, I could replace the current incorrect example (see https://github.com/COMCIFS/magnetic_dic/blob/9d051502375ac6b8bec5205a8af6d9060dca5831/cif_mag.dic#L1295-L1332).

**Comment by brantonc** [comment]
Dear Antanas and James,

I understand your intent now.  I apologize for omitting suitable values in my descriptions of these items.  I include Manu on this message in order to keep him in the loop on this conversation.

The following definition applies to each of the four tags below.
“Symmetry constraints require the cosine part of a given magnetic vector component of a given propagation vector to either be fixed (e.g. at zero) or else be proportional to one of the independent modulation parameters.  The value of this item indicates the independent modulation parameter and proportionality constant.”

Here are the requested example values.

_atom_site_moment_Fourier_param.cos_symmform
0     “Equal to zero.”
mxc2     “Equal to the cosine part of the x component of the magnetic vector amplitude of modulation #2.”
-0.5*mzs1     “Equal to -½ times the sine part of the z component of the magnetic vector amplitude of modulation #1.”
0.03271*myc3     “Equal to 0.03271 times the cosine part of the y component of the magnetic vector amplitude of modulation #3.”

_atom_site_moment_Fourier_param.sin_symmform
0     “Equal to zero.”
mxc2     “Equal to the cosine part of the x component of the magnetic vector amplitude of modulation #2.”
-0.5*mzs1     “Equal to -½ times the sine part of the z component of the magnetic vector amplitude of modulation #1.”
0.03271*myc3     “Equal to 0.03271 times the cosine part of the y component of the magnetic vector amplitude of modulation #3.”

_atom_site_moment_Fourier_param.modulus_symmform
0     “Equal to zero.”
mxm2     “Equal to the modulus of the x component of the magnetic vector amplitude of modulation #2.”
-0.5*mzm1     “Equal to -½ times the modulus of the z component of the magnetic vector amplitude of modulation #1.”
0.03271*mym3     “Equal to 0.03271 times the modulus of the y component of the magnetic vector amplitude of modulation #3.”

_atom_site_moment_Fourier_param.phase_symmform
0        “Equal to 0 degrees.”
-90   “Equal to 90 degrees.”
mxp2     “Equal to the phase of the x component of the magnetic vector amplitude of modulation #2.”
-0.38110*mzp1     “Equal to -0.38110 times the phase of the z component of the magnetic vector amplitude of modulation #1.”
180-myp3     “Equal to 180 degrees minus the phase of the y component of the magnetic vector amplitude of modulation #3.”

Certainly, you can move the extended example you mentioned to the appropriate category description.

Best wishes,
Branton

**Comment by vaitkus** [comment]
@brantonc , thank you, these are very useful examples!

I created a draft PR (#68) that adds these examples, however, I would like to clarify a few things before merging:

1. In you earlier email you provided the following description:
```
Symmetry constraints require the cosine part of a given magnetic vector component of a given propagation vector to either be fixed (e.g. at zero) or else be proportional to one of the independent modulation parameters.  The value of this item indicates the independent modulation parameter and proportionality constant.
```

Would you like for this description to be included alongside the current definition of symmform items?

2. The `_atom_site_moment_Fourier_param.cos_symmform` description provides a detailed description of how the allowed symmform values should be formed. This definition is later on referenced by other symmform items. However, I noticed that some of the examples provided for the `_atom_site_moment_Fourier_param.phase_symmform` data item do not fully conform to this description. Specifically, value `-90` does not match since it is a fixed value other than zero and `180-myp3` does not match since it contains a leading numeric value from which the symbol is subtracted. Maybe  `_atom_site_moment_Fourier_param.cos_symmform`  should get a separate fully written out symmform description which accounts for these numeric values?

3. The `_atom_site_moment_Fourier_param.phase_symmform` contains the following example:
```
-90   “Equal to 90 degrees.”
```
Shouldn't the description read "Equal to -90 degrees"? Or is the sign not important in this case?

4. The `_atom_site_moment_fourier_param.cos_symmform` provides a detailed description of the symmform values. The 4th component is described as:
```
(4) The 4th character is an integer that indicates the modulation vector.
```
Is the integer value assigned to the modulation vector following some well established rules or does the integer refer to a numeric ID that can be found in the same CIF file (e.g. as  `_cell_wave_vector.seq_id` value or similar)?

5. Just a note that the PR in question also updates the `ATOM_SITE_MOMENT_FOURIER_PARAM` category example based on the `_atom_site_moment_fourier_param.cos_symmform` data item example which is now removed from that item. Specifically, the example contained  symmform values without the trailing numeric value `mxs` instead of `mxs1`. See:

https://www.iucr.org/__data/iucr/cifdic_html/3/MAGNETIC_CIF/CATOM_SITE_MOMENT_FOURIER_PARAM.html

**Comment by brantonc** [comment]
Dear Antanas and James,

I have never used the modulus-phase description that some want included in magCIF, and so hadn’t previously thought carefully about the relevant symmforms.  Here is a more careful attempt.

_atom_site_moment_Fourier_param.cos_symmform
“For a given magnetic vector component of the modulation corresponding to given propagation vector, symmetry constraints require the cosine part to be proportional to one of the independent cosine or sine parameters of the modulation.  The value of this item indicates both the independent parameter and the proportionality constant, which may be zero.”
0     “Equal to zero.”
mxc2     “Equal to the cosine part of the x component of the magnetic vector amplitude of modulation #2.”
-0.5*mzs1     “Equal to -½ times the sine part of the z component of the magnetic vector amplitude of modulation #1.”
0.03271*myc3     “Equal to 0.03271 times the cosine part of the y component of the magnetic vector amplitude of modulation #3.”

_atom_site_moment_Fourier_param.sin_symmform
“For a given magnetic vector component of the modulation corresponding to given propagation vector, symmetry constraints require the sine part to be proportional to one of the independent cosine or sine parameters of the modulation.  The value of this item indicates both the independent parameter and the proportionality constant, which may be zero.”
0     “Equal to zero.”
mxc2     “Equal to the cosine part of the x component of the magnetic vector amplitude of modulation #2.”
-0.5*mzs1     “Equal to -½ times the sine part of the z component of the magnetic vector amplitude of modulation #1.”
0.03271*myc3     “Equal to 0.03271 times the cosine part of the y component of the magnetic vector amplitude of modulation #3.”

_atom_site_moment_Fourier_param.modulus_symmform
“For a given magnetic vector component of the modulation corresponding to given propagation vector, symmetry constraints require the modulus to either be zero or equal to one of the independent moduli of the modulation.  The value of this item indicates both the independent modulus and the proportionality constant”
0     “Equal to zero.”
mxm2     “Equal to the modulus of the x component of the magnetic vector amplitude of modulation #2.”
mzm1     “Equal to the modulus of the z component of the magnetic vector amplitude of modulation #1.”

_atom_site_moment_Fourier_param.phase_symmform
“For a given magnetic vector component of the modulation corresponding to given propagation vector, symmetry constraints require the phase to be a linear function of one of the independent phases of the modulation.  The value of this item indicates both the slope (must be +1, 0, or -1) and the intercept of this linear function.”
0        “Equal to 0 degrees.”
-90   “Equal to -90 degrees.”
mxp2     “Equal to the phase of the x component of the magnetic vector amplitude of modulation #2.”
-myp3+15.01938     “Equal to 15.01938 degrees minus the phase of the y component of the magnetic vector amplitude of modulation #3.”

Certainly, you can move the extended example you mentioned to the appropriate category description.

Best wishes,
Branton

**Comment by brantonc** [comment]
Regarding your point (4) below, the 4th character corresponds to an integer value of
_atom_site_moment_Fourier.wave_vector_seq_id.
In the extended example you linked below, each instance of “mxs” should be “mxs1” because the entire triple-k modulation has only on independent parameter, which is the sine component of the first wave.

**Comment by vaitkus** [comment]
Dear Branton,

thank you for the valuable comments. I updated the definitions and examples accordingly. Furthermore, I copied the earlier description of `atom_site_moment_Fourier_param.cos_symmform` and tried adapting it to the other symmform definitions in question. Do I understand correctly, that string `mxp1` would never appear as a value of  `atom_site_moment_Fourier_param.sin_symmform`, since for the sin symmform the third character is limit to either `s` (sin) or `c` (cos)?

It would also be great if you could review the final pull request #68, just to see if did not mix anything up.

Sincerely
Antanas

**Comment by brantonc** [comment]
Dear Antanas,

You are right.  The sin/cos approach will tie sine and cosine terms to one another.  The modulus/phase approach will tie moduli together and will tie phases together, but will not tie moduli to phases and will not tie moduli or phases to sine or cosine terms.

Branton
